name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir:
          - "1.15.8"
          - "1.18.4"
        otp:
          - "25.1.2"
          - "28.0.2"
        exclude:
          - elixir: "1.15.8"
            otp: "28.0.2"
    env:
      MIX_ENV: test
      elixir: ${{ matrix.elixir }}
      otp: ${{ matrix.otp }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ env.elixir }}
          otp-version: ${{ env.otp }}
          build-flags: --all-warnings --warnings-as-errors

      - name: Run Tests
        run: mix coveralls.json --warnings-as-errors --include integration --include timing

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./cover/excoveralls.json
          slug: s3cur3/okay_weather
        if: ${{ matrix.elixir == '1.18.4' && matrix.otp == '28.0.2' }}

